### ISSUE TITLE
About code reproduction

### ISSUE THREAD

**Issue by 572263440** [T-urning/MultiTaskBasedEventDetection#1]
你好，我想问一下，这个代码是 Event Detection via Context Understanding Based on Multi-task Learning 这篇论文的复现嘛？
Hello, I would like to ask, is this code a reproduction of the paper Event Detection via Context Understanding Based on Multi-task Learning?

**Comment by T-urning** [comment]
是的

**Comment by 572263440** [comment]
> 是的

非常感谢您的回复！！！
